# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc03cdfefe5f1fb4d9c7299facb2d1f7ac182113ade57827df5ef16121ff3cb01b814bfe379eb1b077b3eb1dc50ffdfe3ba72bcc9eab2e91ab56294a038dcfed

test:
  secret_key_base: 908862eddff6b7d3349ceb138abefed05e7c68da420bf259c44b1ee9f05b1ab322c3c3afd1586c03014f96aaa33179b85891c103e69c7973987d6b5157723913

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
